import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@afl/db";
import { runAgent, runKickoff, runCombine } from "@afl/agents";

function parsePayload(input: string): Record<string, unknown> {
  try {
    return JSON.parse(input || "{}") as Record<string, unknown>;
  } catch {
    return {};
  }
}

export async function POST(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const runbook = await prisma.runbook.findUnique({ where: { id } });
  if (!runbook) return NextResponse.json({ error: "Runbook not found" }, { status: 404 });
  if (!runbook.isEnabled) return NextResponse.json({ error: "Runbook is disabled" }, { status: 409 });

  const runbookRun = await prisma.runbookRun.create({
    data: {
      runbookId: runbook.id,
      status: "RUNNING",
      startedAt: new Date(),
    },
  });

  await prisma.eventLog.create({
    data: {
      agentId: runbook.ownerAgentId ?? undefined,
      type: "RUNBOOK_RUN_STARTED",
      summary: `Runbook started: ${runbook.name}`,
      entityType: "RUNBOOK",
      entityId: runbook.id,
      runbookId: runbook.id,
      runbookRunId: runbookRun.id,
      meta: JSON.stringify({ runbookRunId: runbookRun.id, actionType: runbook.actionType }),
    },
  });

  try {
    const payload = parsePayload(runbook.actionPayloadJson);
    let outputSummary = "";

    if (runbook.actionType === "RUN_AGENT") {
      const agentId = String(payload.agentId ?? "");
      if (!agentId) throw new Error("RUN_AGENT requires payload.agentId");
      const result = await runAgent(agentId);
      outputSummary = result.summary;
    } else if (runbook.actionType === "RUN_KICKOFF") {
      const result = await runKickoff();
      outputSummary = `Kickoff: ${result.totalTasks} tasks, ${result.totalApprovals} approvals`;
    } else if (runbook.actionType === "RUN_COMBINE") {
      const agentId = String(payload.agentId ?? "");
      const runType = String(payload.runType ?? "COMBINE") as "COMBINE" | "SCRIMMAGE";
      if (!agentId) throw new Error("RUN_COMBINE requires payload.agentId");
      const result = await runCombine(agentId, runType, Number(payload.seed ?? 42));
      outputSummary = `Combine ${result.combineRunId}: overall ${result.scoreOverall}`;
    } else if (runbook.actionType === "GENERATE_REPORT") {
      const targetAgentId = String(payload.targetAgentId ?? "commissioner");
      const agent = await prisma.agent.findUnique({ where: { id: targetAgentId } });
      if (!agent) throw new Error("Report target agent not found");
      const message = await prisma.message.create({
        data: {
          agentId: agent.id,
          type: "REPORT",
          title: `${agent.name} Runbook Report`,
          body: `Generated by runbook ${runbook.name} at ${new Date().toISOString()}`,
          meta: JSON.stringify({ runbookId: runbook.id, runbookRunId: runbookRun.id }),
        },
      });
      await prisma.eventLog.create({
        data: {
          agentId: agent.id,
          type: "AGENT_WEEKLY_REPORT",
          summary: `${agent.name} report generated via runbook.`,
          entityType: "AGENT",
          entityId: agent.id,
          meta: JSON.stringify({ messageId: message.id, runbookId: runbook.id }),
        },
      });
      outputSummary = `Report generated for ${agent.name}`;
    } else {
      throw new Error(`Unsupported action type: ${runbook.actionType}`);
    }

    const finished = await prisma.runbookRun.update({
      where: { id: runbookRun.id },
      data: {
        status: "COMPLETED",
        finishedAt: new Date(),
        outputSummary,
      },
    });

    await prisma.eventLog.create({
      data: {
        agentId: runbook.ownerAgentId ?? undefined,
        type: "RUNBOOK_RUN_COMPLETED",
        summary: `Runbook completed: ${runbook.name}`,
        entityType: "RUNBOOK",
        entityId: runbook.id,
        runbookId: runbook.id,
        runbookRunId: runbookRun.id,
        meta: JSON.stringify({ outputSummary }),
      },
    });

    return NextResponse.json(finished);
  } catch (error) {
    const failed = await prisma.runbookRun.update({
      where: { id: runbookRun.id },
      data: {
        status: "FAILED",
        finishedAt: new Date(),
        outputSummary: error instanceof Error ? error.message : String(error),
      },
    });

    await prisma.eventLog.create({
      data: {
        agentId: runbook.ownerAgentId ?? undefined,
        type: "RUNBOOK_RUN_FAILED",
        summary: `Runbook failed: ${runbook.name}`,
        entityType: "RUNBOOK",
        entityId: runbook.id,
        runbookId: runbook.id,
        runbookRunId: runbookRun.id,
        meta: JSON.stringify({ error: error instanceof Error ? error.message : String(error) }),
      },
    });

    return NextResponse.json(failed, { status: 500 });
  }
}
