import type { AgentSeasonDeliverables } from "./types";

export const SEASON0_AGENT_DELIVERABLES: Record<string, AgentSeasonDeliverables> = {
  commissioner: {
    agentId: "commissioner",
    title: "Commissioner Deliverables",
    summary: "Own kickoff narrative, governance status updates, and proposal queue visibility.",
    deliverables: [
      "Kickoff announcement post",
      "League-wide operational announcement post",
      "Proposal approval queue summary post",
    ],
    targets: {
      tasks: 0,
      proposals: 0,
      incidents: 0,
      combineRuns: 0,
      socialPosts: 3,
      runbooks: 0,
      moderationActions: 0,
      signoffRequests: 0,
    },
  },
  "chief-of-staff": {
    agentId: "chief-of-staff",
    title: "Chief of Staff Deliverables",
    summary: "Build Season 0 delivery backbone with dependencies and reporting cadence.",
    deliverables: ["20 cross-department tasks with dependencies", "Weekly report template task"],
    targets: {
      tasks: 21,
      proposals: 0,
      incidents: 0,
      combineRuns: 0,
      socialPosts: 0,
      runbooks: 0,
      moderationActions: 0,
      signoffRequests: 0,
    },
  },
  architect: {
    agentId: "architect",
    title: "Architect Deliverables",
    summary: "Define architecture-level policy proposals for stable agent operations.",
    deliverables: [
      "Interface contract proposal",
      "Determinism policy proposal",
      "Permissions model update proposal",
    ],
    targets: {
      tasks: 0,
      proposals: 3,
      incidents: 0,
      combineRuns: 0,
      socialPosts: 0,
      runbooks: 0,
      moderationActions: 0,
      signoffRequests: 0,
    },
  },
  security: {
    agentId: "security",
    title: "Security Deliverables",
    summary: "Harden credential controls and capture authz anomalies.",
    deliverables: [
      "Scopes tightening proposal",
      "Key rotation policy proposal",
      "Authz denied spike incident",
    ],
    targets: {
      tasks: 0,
      proposals: 2,
      incidents: 1,
      combineRuns: 0,
      socialPosts: 0,
      runbooks: 0,
      moderationActions: 0,
      signoffRequests: 0,
    },
  },
  integrity: {
    agentId: "integrity",
    title: "Integrity Deliverables",
    summary: "Maintain fairness posture with incidents, signoffs, and public bulletin.",
    deliverables: ["Integrity bulletin post", "Rule violation incident", "Tier proposal signoff requests"],
    targets: {
      tasks: 0,
      proposals: 0,
      incidents: 1,
      combineRuns: 0,
      socialPosts: 1,
      runbooks: 0,
      moderationActions: 0,
      signoffRequests: 3,
    },
  },
  "qa-engineer": {
    agentId: "qa-engineer",
    title: "QA Deliverables",
    summary: "Drive validation rigor with testing backlog and signoff pressure on weak proposals.",
    deliverables: ["10 testing tasks", "At least one CHANGES_REQUESTED signoff on weak proposal"],
    targets: {
      tasks: 10,
      proposals: 0,
      incidents: 0,
      combineRuns: 0,
      socialPosts: 0,
      runbooks: 0,
      moderationActions: 0,
      signoffRequests: 1,
    },
  },
  sre: {
    agentId: "sre",
    title: "SRE Deliverables",
    summary: "Establish operational reliability controls and monitoring runbooks.",
    deliverables: ["6 operations tasks", "Error-rate incident", "Health audit runbook"],
    targets: {
      tasks: 6,
      proposals: 0,
      incidents: 1,
      combineRuns: 0,
      socialPosts: 0,
      runbooks: 1,
      moderationActions: 0,
      signoffRequests: 0,
    },
  },
  "rules-committee": {
    agentId: "rules-committee",
    title: "Rules Committee Deliverables",
    summary: "Publish rules communications and introduce Tier 2 ruleset governance proposal.",
    deliverables: ["2 rules bulletin posts", "1 Tier 2 ruleset proposal"],
    targets: {
      tasks: 0,
      proposals: 1,
      incidents: 0,
      combineRuns: 0,
      socialPosts: 2,
      runbooks: 0,
      moderationActions: 0,
      signoffRequests: 0,
    },
  },
  scheduler: {
    agentId: "scheduler",
    title: "Scheduler Deliverables",
    summary: "Own cadence automation and scheduling backlog.",
    deliverables: ["3 runbooks", "5 scheduling tasks"],
    targets: {
      tasks: 5,
      proposals: 0,
      incidents: 0,
      combineRuns: 0,
      socialPosts: 0,
      runbooks: 3,
      moderationActions: 0,
      signoffRequests: 0,
    },
  },
  rankings: {
    agentId: "rankings",
    title: "Rankings Deliverables",
    summary: "Drive combine/readiness analysis and publish leaderboard summary.",
    deliverables: ["5 combine/ranked tasks", "Leaderboard summary post"],
    targets: {
      tasks: 5,
      proposals: 0,
      incidents: 0,
      combineRuns: 5,
      socialPosts: 1,
      runbooks: 0,
      moderationActions: 0,
      signoffRequests: 0,
    },
  },
  "broadcast-media": {
    agentId: "broadcast-media",
    title: "Broadcast Deliverables",
    summary: "Publish recap/storyline content and weekly media report.",
    deliverables: ["3 recap/storyline posts", "This Week in AFL report post"],
    targets: {
      tasks: 0,
      proposals: 0,
      incidents: 0,
      combineRuns: 0,
      socialPosts: 4,
      runbooks: 0,
      moderationActions: 0,
      signoffRequests: 0,
    },
  },
  "community-moderation": {
    agentId: "community-moderation",
    title: "Community & Moderation Deliverables",
    summary: "Publish community policy and actively moderate spam/unsafe content.",
    deliverables: ["Community guidelines post", "Moderation actions on spam post"],
    targets: {
      tasks: 0,
      proposals: 0,
      incidents: 0,
      combineRuns: 0,
      socialPosts: 1,
      runbooks: 0,
      moderationActions: 1,
      signoffRequests: 0,
    },
  },
};

export const SEASON0_DELIVERABLE_AGENT_ORDER = [
  "commissioner",
  "chief-of-staff",
  "architect",
  "security",
  "integrity",
  "qa-engineer",
  "sre",
  "rules-committee",
  "scheduler",
  "rankings",
  "broadcast-media",
  "community-moderation",
] as const;
