// Deterministic task templates per department/agent

export interface TaskTemplate {
  title: string;
  description: string;
  department: string;
  tier: number;
  acceptanceCriteria: string;
  riskNotes: string;
  testPlan: string;
  rollbackPlan: string;
  requiresApproval: boolean;
  approvalSummary?: string;
}

export const TASK_TEMPLATES: Record<string, TaskTemplate[]> = {
  commissioner: [
    {
      title: "Define Season 0 Constitution",
      description: "Draft and ratify the foundational rules governing AFL Season 0 operations.",
      department: "COMMISSIONER",
      tier: 3,
      acceptanceCriteria: "Constitution ratified with all department heads signing off.",
      riskNotes: "Ambiguity in rules could cause disputes; requires legal review.",
      testPlan: "Review draft with Rules Committee; simulate 3 edge-case scenarios.",
      rollbackPlan: "Revert to prior interim rules document.",
      requiresApproval: true,
      approvalSummary: "Tier 3: Ratify AFL Season 0 Constitution — multi-sig required.",
    },
    {
      title: "Establish Commissioner Veto Protocol",
      description: "Define the conditions and process for Commissioner veto of agent proposals.",
      department: "COMMISSIONER",
      tier: 2,
      acceptanceCriteria: "Protocol documented, tested with 2 simulated veto scenarios.",
      riskNotes: "Overuse of veto could block league progress.",
      testPlan: "Run 2 simulated Tier 2 proposals through veto workflow.",
      rollbackPlan: "Remove veto gate and escalate to manual review.",
      requiresApproval: true,
      approvalSummary: "Tier 2: Commissioner veto protocol sign-off needed.",
    },
  ],
  architect: [
    {
      title: "Design Control Room Data Model",
      description: "Finalize Prisma schema for Agent, Task, Approval, EventLog, LeagueState.",
      department: "TECHNOLOGY",
      tier: 1,
      acceptanceCriteria: "Schema migrated to SQLite; all relations verified with seed data.",
      riskNotes: "Schema changes require migration; breaking changes need rollback plan.",
      testPlan: "Run seed script and verify row counts in Prisma Studio.",
      rollbackPlan: "Restore prior migration snapshot.",
      requiresApproval: false,
    },
    {
      title: "Define API Contract for Agent Orchestration",
      description: "Document and implement REST endpoints for agent runs, tasks, approvals, feed.",
      department: "TECHNOLOGY",
      tier: 1,
      acceptanceCriteria: "All endpoints return correct shapes; Zod validation passes.",
      riskNotes: "Breaking API changes will require client updates.",
      testPlan: "curl each endpoint and assert status + shape.",
      rollbackPlan: "Version endpoints under /api/v1.",
      requiresApproval: false,
    },
    {
      title: "Architect SSE Feed Pipeline",
      description: "Design and implement the server-sent events pipeline for real-time EventLog updates.",
      department: "TECHNOLOGY",
      tier: 1,
      acceptanceCriteria: "Feed page shows live events within 3 seconds of DB write.",
      riskNotes: "Long-lived connections may exhaust server resources under load.",
      testPlan: "Open two browser tabs; trigger agent run; verify both see new event.",
      rollbackPlan: "Fall back to polling /api/feed every 5s.",
      requiresApproval: false,
    },
    {
      title: "Define Tier Enforcement Architecture",
      description: "Architect how Tier 0-3 governance is enforced across API, agents, and UI.",
      department: "TECHNOLOGY",
      tier: 3,
      acceptanceCriteria: "Tier 3 proposals blocked without multi-sig; seasonLock defers Tier 2/3.",
      riskNotes: "Bypassing tier checks is a critical security risk.",
      testPlan: "Attempt Tier 3 proposal without multi-sig; expect rejection.",
      rollbackPlan: "Revert to manual commissioner approval for all tiers.",
      requiresApproval: true,
      approvalSummary: "Tier 3: Approve tier enforcement architecture — engine-level change.",
    },
  ],
  security: [
    {
      title: "Implement API Rate Limiting",
      description: "Add rate limiting to all POST endpoints to prevent agent run abuse.",
      department: "SECURITY",
      tier: 1,
      acceptanceCriteria: "POST /api/agents/run limited to 10 req/min per IP.",
      riskNotes: "Overly aggressive limits could block legitimate orchestration.",
      testPlan: "Send 15 rapid requests; verify 429 on request 11.",
      rollbackPlan: "Remove rate limiting middleware.",
      requiresApproval: false,
    },
    {
      title: "Audit Agent Permission Model",
      description: "Review and verify each agent's permissions match their role card.",
      department: "SECURITY",
      tier: 2,
      acceptanceCriteria: "All agents have correct maxProposalTier; no privilege escalation paths.",
      riskNotes: "Overpermissioned agents could create unauthorized Tier 3 proposals.",
      testPlan: "Run automated permission matrix check against role cards.",
      rollbackPlan: "Revert permissions to conservative defaults.",
      requiresApproval: true,
      approvalSummary: "Tier 2: Agent permission audit results require Commissioner sign-off.",
    },
    {
      title: "Define Incident Response Runbook",
      description: "Create runbook for responding to integrity alerts and security incidents.",
      department: "SECURITY",
      tier: 1,
      acceptanceCriteria: "Runbook covers: data breach, agent takeover, score manipulation.",
      riskNotes: "Untested runbooks may fail under real incident pressure.",
      testPlan: "Tabletop exercise with Commissioner and Security agents.",
      rollbackPlan: "Escalate all incidents to Commissioner manually.",
      requiresApproval: false,
    },
  ],
  integrity: [
    {
      title: "Draft Anti-Tampering Policy",
      description: "Define rules against score manipulation, agent collusion, and data tampering.",
      department: "LEGAL_COMPLIANCE",
      tier: 2,
      acceptanceCriteria: "Policy covers all 3 tampering vectors; ratified by Commissioner.",
      riskNotes: "Weak policy leaves league vulnerable to manipulation.",
      testPlan: "Simulate 2 tampering attempts and verify detection.",
      rollbackPlan: "Apply interim no-tolerance policy.",
      requiresApproval: true,
      approvalSummary: "Tier 2: Anti-tampering policy requires Commissioner sign-off.",
    },
    {
      title: "Set Up Integrity Alert Pipeline",
      description: "Wire integrity alerts from EventLog to /ops dashboard with severity levels.",
      department: "LEGAL_COMPLIANCE",
      tier: 1,
      acceptanceCriteria: "Alerts appear in /ops within 5s of anomalous event creation.",
      riskNotes: "Alert fatigue from false positives.",
      testPlan: "Inject synthetic anomaly event; verify ops alert fires.",
      rollbackPlan: "Manual ops log review.",
      requiresApproval: false,
    },
  ],
  "program-manager": [
    {
      title: "Create Season 0 Backlog",
      description: "Compile and prioritize all Season 0 infrastructure tasks into the Kanban board.",
      department: "FOOTBALL_OPS",
      tier: 1,
      acceptanceCriteria: ">=30 tasks in BACKLOG; each has tier, department, acceptance criteria.",
      riskNotes: "Under-scoped backlog will delay season launch.",
      testPlan: "Count tasks in /tasks; verify all have required fields.",
      rollbackPlan: "Re-run Season 0 Kickoff to regenerate backlog.",
      requiresApproval: false,
    },
    {
      title: "Define Sprint 1 Scope",
      description: "Select the first 8 tasks to move from BACKLOG to IN_PROGRESS for Sprint 1.",
      department: "FOOTBALL_OPS",
      tier: 1,
      acceptanceCriteria: "8 tasks in IN_PROGRESS with assignees set.",
      riskNotes: "Overloading sprint capacity will block delivery.",
      testPlan: "Verify assignee count vs agent capacity.",
      rollbackPlan: "Return tasks to BACKLOG.",
      requiresApproval: false,
    },
    {
      title: "Establish Definition of Done",
      description: "Document what 'DONE' means for Season 0 tasks (tests passing, docs updated, log entry).",
      department: "FOOTBALL_OPS",
      tier: 1,
      acceptanceCriteria: "DoD documented and linked from task card template.",
      riskNotes: "Vague DoD leads to scope creep.",
      testPlan: "Apply DoD to 3 sample tasks and validate.",
      rollbackPlan: "Revert to informal done criteria.",
      requiresApproval: false,
    },
  ],
  "backend-engineer": [
    {
      title: "Implement Task CRUD API",
      description: "Build GET /api/tasks and PATCH /api/tasks/:id with Zod validation.",
      department: "TECHNOLOGY",
      tier: 1,
      acceptanceCriteria: "All task fields patchable; Zod rejects invalid shapes.",
      riskNotes: "Direct DB writes without validation risk data corruption.",
      testPlan: "Integration test: create task, patch status, verify DB.",
      rollbackPlan: "Roll back to last stable migration.",
      requiresApproval: false,
    },
    {
      title: "Wire Prisma Singleton Pattern",
      description: "Ensure PrismaClient is a singleton in Next.js to avoid connection pool exhaustion.",
      department: "TECHNOLOGY",
      tier: 1,
      acceptanceCriteria: "Single PrismaClient instance across all API routes in dev and prod.",
      riskNotes: "Multiple instances in dev HMR cause 'Too many connections' errors.",
      testPlan: "Check globalThis for prisma instance after 10 requests.",
      rollbackPlan: "Instantiate new client per request as fallback.",
      requiresApproval: false,
    },
    {
      title: "Implement EventLog Write Helper",
      description: "Create shared utility for writing EventLog entries from any API route.",
      department: "TECHNOLOGY",
      tier: 1,
      acceptanceCriteria: "All agent runs and approval actions write to EventLog.",
      riskNotes: "Missing log entries break feed accuracy.",
      testPlan: "Run agent; verify EventLog row exists with correct type.",
      rollbackPlan: "Manual log writes per route.",
      requiresApproval: false,
    },
  ],
  "qa-engineer": [
    {
      title: "Write API Integration Test Suite",
      description: "Cover all /api/* routes with happy-path and error-case tests.",
      department: "TECHNOLOGY",
      tier: 1,
      acceptanceCriteria: "100% route coverage; all tests pass in CI.",
      riskNotes: "Untested edge cases may surface in production.",
      testPlan: "Jest + supertest hitting local SQLite test DB.",
      rollbackPlan: "Manual API smoke test checklist.",
      requiresApproval: false,
    },
    {
      title: "Validate Zod Schemas Against Prisma Output",
      description: "Ensure Zod request schemas are compatible with Prisma response shapes.",
      department: "TECHNOLOGY",
      tier: 1,
      acceptanceCriteria: "No type mismatches between Zod types and Prisma model types.",
      riskNotes: "Silent type drift between schema and DB.",
      testPlan: "TypeScript strict mode + tsc --noEmit in CI.",
      rollbackPlan: "Add runtime shape assertion middleware.",
      requiresApproval: false,
    },
    {
      title: "End-to-End Kickoff Test",
      description: "Run Season 0 Kickoff and verify >=30 tasks, approvals, and feed events are created.",
      department: "TECHNOLOGY",
      tier: 1,
      acceptanceCriteria: "POST /api/season0/kickoff returns tasksCreated>=30, approvalsCreated>=5.",
      riskNotes: "Idempotency issues may cause duplicate tasks on re-run.",
      testPlan: "Run kickoff twice; assert no duplicate titles.",
      rollbackPlan: "Add unique constraint on task title.",
      requiresApproval: false,
    },
  ],
  sre: [
    {
      title: "Configure SQLite WAL Mode",
      description: "Enable Write-Ahead Logging on SQLite for better concurrent read performance.",
      department: "TECHNOLOGY",
      tier: 1,
      acceptanceCriteria: "PRAGMA journal_mode returns 'wal' after migration.",
      riskNotes: "WAL files (.wal, .shm) need to be gitignored.",
      testPlan: "Run PRAGMA check post-migration.",
      rollbackPlan: "Revert to DELETE journal mode.",
      requiresApproval: false,
    },
    {
      title: "Define Health Check Endpoint",
      description: "Implement GET /api/health returning DB connectivity and league status.",
      department: "TECHNOLOGY",
      tier: 1,
      acceptanceCriteria: "Returns 200 with { db: 'ok', season: 0, locked: false }.",
      riskNotes: "Health check itself could cause DB load.",
      testPlan: "curl /api/health 100 times; assert p99 < 50ms.",
      rollbackPlan: "Remove endpoint.",
      requiresApproval: false,
    },
    {
      title: "Deploy Log Retention Policy",
      description: "Define EventLog retention — archive events older than 90 days.",
      department: "TECHNOLOGY",
      tier: 2,
      acceptanceCriteria: "Archival job runs nightly; feed unaffected.",
      riskNotes: "Premature deletion loses audit trail.",
      testPlan: "Seed 100 old events; run archiver; verify count.",
      rollbackPlan: "Disable archival job.",
      requiresApproval: true,
      approvalSummary: "Tier 2: EventLog retention policy — data governance sign-off required.",
    },
  ],
  "rules-committee": [
    {
      title: "Draft Scoring Engine Specification",
      description: "Define how Season 0 games are scored — touchdowns, field goals, penalties.",
      department: "LEGAL_COMPLIANCE",
      tier: 3,
      acceptanceCriteria: "Spec covers all scoring scenarios; reviewed by Commissioner.",
      riskNotes: "Ambiguous scoring rules invalidate all game results.",
      testPlan: "Walk through 5 game scenarios manually.",
      rollbackPlan: "Use standard NFL scoring rules as interim.",
      requiresApproval: true,
      approvalSummary: "Tier 3: Scoring engine spec — Commissioner + multi-sig required.",
    },
    {
      title: "Define Eligibility Rules",
      description: "Establish player/team eligibility criteria for Season 0.",
      department: "LEGAL_COMPLIANCE",
      tier: 2,
      acceptanceCriteria: "Eligibility rules cover: registration, injury, suspension.",
      riskNotes: "Edge cases in eligibility may cause disputes.",
      testPlan: "Apply rules to 5 hypothetical player scenarios.",
      rollbackPlan: "Manual eligibility review by Commissioner.",
      requiresApproval: true,
      approvalSummary: "Tier 2: Eligibility rules require Commissioner sign-off.",
    },
    {
      title: "Ratify Replay / Challenge System Rules",
      description: "Define conditions under which plays can be reviewed and challenged.",
      department: "LEGAL_COMPLIANCE",
      tier: 2,
      acceptanceCriteria: "Challenge rules cover: timing, challenge limit, success criteria.",
      riskNotes: "Ambiguous challenge rules delay game flow.",
      testPlan: "Simulate 3 challenge scenarios.",
      rollbackPlan: "No challenge system — all calls final.",
      requiresApproval: true,
      approvalSummary: "Tier 2: Replay/challenge rules require Commissioner sign-off.",
    },
  ],
  scheduler: [
    {
      title: "Build Season 0 Game Schedule",
      description: "Generate schedule for all Season 0 games including dates and matchups.",
      department: "FOOTBALL_OPS",
      tier: 1,
      acceptanceCriteria: "Schedule has >= 8 games; no team plays twice in same week.",
      riskNotes: "Schedule conflicts cause game forfeits.",
      testPlan: "Verify schedule constraints programmatically.",
      rollbackPlan: "Manual schedule assignment.",
      requiresApproval: false,
    },
    {
      title: "Define Bye Week Policy",
      description: "Establish rules for bye weeks — rotation, fairness, playoff impact.",
      department: "FOOTBALL_OPS",
      tier: 1,
      acceptanceCriteria: "Every team gets at least 1 bye; playoff seeding unaffected.",
      riskNotes: "Unequal bye weeks disadvantage some teams.",
      testPlan: "Verify bye distribution across all teams.",
      rollbackPlan: "Remove bye weeks from Season 0.",
      requiresApproval: false,
    },
  ],
  rankings: [
    {
      title: "Define Rankings Algorithm",
      description: "Design the formula for team rankings: wins, point differential, SOS.",
      department: "FOOTBALL_OPS",
      tier: 3,
      acceptanceCriteria: "Algorithm produces deterministic rankings given same inputs.",
      riskNotes: "Flawed algorithm creates wrong playoff seedings.",
      testPlan: "Apply algorithm to 3 sample standings; verify ordering.",
      rollbackPlan: "Fall back to win-loss record only.",
      requiresApproval: true,
      approvalSummary: "Tier 3: Rankings algorithm — affects scoring engine; Commissioner + multi-sig.",
    },
    {
      title: "Implement Power Rankings Dashboard Tile",
      description: "Add a power rankings card to the Commissioner dashboard.",
      department: "FOOTBALL_OPS",
      tier: 1,
      acceptanceCriteria: "Top 5 teams shown with rank, record, and trend arrow.",
      riskNotes: "Rankings before enough games played are meaningless.",
      testPlan: "Seed mock standings; verify tile displays correctly.",
      rollbackPlan: "Hide tile until 4+ games played.",
      requiresApproval: false,
    },
  ],
};
