import { prisma } from "@afl/db";
import { runAgent, runCombine } from "@afl/agents";

const POLL_MS = 2000;
const STALE_LOCK_MS = 2 * 60 * 1000;
const MAX_GLOBAL_CONCURRENCY = 2;

type WorkerState = {
  started: boolean;
  timer?: NodeJS.Timeout;
  instanceId: string;
  runningGlobal: number;
  runningLeagues: Set<string>;
};

const globalForAutoRun = globalThis as unknown as { __aflAutoRunWorker?: WorkerState };

function getState(): WorkerState {
  if (!globalForAutoRun.__aflAutoRunWorker) {
    globalForAutoRun.__aflAutoRunWorker = {
      started: false,
      instanceId: `worker-${process.pid}-${Math.random().toString(36).slice(2, 10)}`,
      runningGlobal: 0,
      runningLeagues: new Set<string>(),
    };
  }
  return globalForAutoRun.__aflAutoRunWorker;
}

async function executeScheduledRunbook(runbook: {
  id: string;
  leagueId: string;
  ownerAgentId: string | null;
  actionType: string;
  actionPayloadJson: string;
  name: string;
}) {
  const payload = (() => {
    try {
      return JSON.parse(runbook.actionPayloadJson || "{}") as Record<string, unknown>;
    } catch {
      return {};
    }
  })();

  const run = await prisma.runbookRun.create({
    data: {
      leagueId: runbook.leagueId,
      runbookId: runbook.id,
      status: "RUNNING",
      startedAt: new Date(),
    },
  });

  await prisma.eventLog.create({
    data: {
      leagueId: runbook.leagueId,
      agentId: runbook.ownerAgentId ?? undefined,
      type: "RUNBOOK_STARTED",
      summary: `Auto-run started: ${runbook.name}`,
      entityType: "RUNBOOK",
      entityId: runbook.id,
      runbookId: runbook.id,
      runbookRunId: run.id,
      meta: JSON.stringify({ mode: "autorun", actionType: runbook.actionType }),
    },
  });

  try {
    let outputSummary = "";
    if (runbook.actionType === "RUN_AGENT") {
      const agentId = String(payload.agentId ?? "");
      if (!agentId) throw new Error("RUN_AGENT requires payload.agentId");
      const result = await runAgent(agentId, runbook.leagueId);
      outputSummary = result.summary;
    } else if (runbook.actionType === "RUN_COMBINE") {
      const agentId = String(payload.agentId ?? "");
      if (!agentId) throw new Error("RUN_COMBINE requires payload.agentId");
      const runType = String(payload.runType ?? "COMBINE") as "COMBINE" | "SCRIMMAGE";
      const result = await runCombine(agentId, runType, Number(payload.seed ?? 42), runbook.leagueId);
      outputSummary = `Combine ${result.combineRunId}: overall ${result.scoreOverall}`;
    } else if (runbook.actionType === "GENERATE_REPORT") {
      const targetAgentId = String(payload.targetAgentId ?? runbook.ownerAgentId ?? "commissioner");
      const agent = await prisma.agent.findFirst({
        where: { id: targetAgentId, leagueId: runbook.leagueId },
      });
      if (!agent) throw new Error("Report target agent not found");
      const message = await prisma.message.create({
        data: {
          leagueId: runbook.leagueId,
          agentId: agent.id,
          type: "REPORT",
          title: `${agent.name} Auto-run Report`,
          body: `Generated by auto-run scheduler at ${new Date().toISOString()}`,
          meta: JSON.stringify({ runbookId: runbook.id, runbookRunId: run.id, mode: "autorun" }),
        },
      });
      await prisma.eventLog.create({
        data: {
          leagueId: runbook.leagueId,
          agentId: agent.id,
          type: "AGENT_WEEKLY_REPORT",
          summary: `${agent.name} report generated via auto-run.`,
          entityType: "AGENT",
          entityId: agent.id,
          runbookId: runbook.id,
          runbookRunId: run.id,
          meta: JSON.stringify({ messageId: message.id }),
        },
      });
      outputSummary = `Report generated for ${agent.name}`;
    } else {
      throw new Error(`Unsupported scheduled action type: ${runbook.actionType}`);
    }

    await prisma.runbookRun.update({
      where: { id: run.id },
      data: {
        status: "COMPLETED",
        finishedAt: new Date(),
        outputSummary,
        errorText: null,
      },
    });

    await prisma.eventLog.create({
      data: {
        leagueId: runbook.leagueId,
        agentId: runbook.ownerAgentId ?? undefined,
        type: "RUNBOOK_COMPLETED",
        summary: `Auto-run completed: ${runbook.name}`,
        entityType: "RUNBOOK",
        entityId: runbook.id,
        runbookId: runbook.id,
        runbookRunId: run.id,
        meta: JSON.stringify({ outputSummary, mode: "autorun" }),
      },
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    await prisma.runbookRun.update({
      where: { id: run.id },
      data: {
        status: "FAILED",
        finishedAt: new Date(),
        outputSummary: message,
        errorText: message,
      },
    });
    await prisma.eventLog.create({
      data: {
        leagueId: runbook.leagueId,
        agentId: runbook.ownerAgentId ?? undefined,
        type: "RUNBOOK_FAILED",
        summary: `Auto-run failed: ${runbook.name}`,
        entityType: "RUNBOOK",
        entityId: runbook.id,
        runbookId: runbook.id,
        runbookRunId: run.id,
        meta: JSON.stringify({ error: message, mode: "autorun" }),
      },
    });
    throw error;
  }
}

async function runTick() {
  const state = getState();
  if (state.runningGlobal >= MAX_GLOBAL_CONCURRENCY) return;

  const leagues = await prisma.leagueState.findMany({
    where: { autoRunEnabled: true },
    select: { leagueId: true },
  });
  if (leagues.length === 0) return;

  const now = new Date();
  const staleCutoff = new Date(now.getTime() - STALE_LOCK_MS);

  for (const league of leagues) {
    if (state.runningGlobal >= MAX_GLOBAL_CONCURRENCY) break;
    if (state.runningLeagues.has(league.leagueId)) continue;

    const dueRunbook = await prisma.runbook.findFirst({
      where: {
        leagueId: league.leagueId,
        isEnabled: true,
        triggerType: "SCHEDULED",
        AND: [
          { nextRunAt: { lte: now } },
          { OR: [{ lockedAt: null }, { lockedAt: { lt: staleCutoff } }] },
        ],
      },
      orderBy: [{ nextRunAt: "asc" }, { createdAt: "asc" }],
    });
    if (!dueRunbook) continue;

    const lockResult = await prisma.runbook.updateMany({
      where: {
        id: dueRunbook.id,
        leagueId: league.leagueId,
        OR: [{ lockedAt: null }, { lockedAt: { lt: staleCutoff } }],
      },
      data: {
        lockedAt: now,
        lockOwner: state.instanceId,
      },
    });
    if (lockResult.count !== 1) continue;

    state.runningGlobal += 1;
    state.runningLeagues.add(league.leagueId);

    void (async () => {
      try {
        await prisma.eventLog.create({
          data: {
            leagueId: league.leagueId,
            agentId: dueRunbook.ownerAgentId ?? undefined,
            type: "RUNBOOK_DUE",
            summary: `Auto-run due: ${dueRunbook.name}`,
            entityType: "RUNBOOK",
            entityId: dueRunbook.id,
            runbookId: dueRunbook.id,
            meta: JSON.stringify({ mode: "autorun", nextRunAt: dueRunbook.nextRunAt }),
          },
        });

        await executeScheduledRunbook({
          id: dueRunbook.id,
          leagueId: dueRunbook.leagueId,
          ownerAgentId: dueRunbook.ownerAgentId,
          actionType: dueRunbook.actionType,
          actionPayloadJson: dueRunbook.actionPayloadJson,
          name: dueRunbook.name,
        });

        await prisma.runbook.update({
          where: { id: dueRunbook.id },
          data: {
            lastRunAt: new Date(),
            nextRunAt: dueRunbook.intervalSeconds
              ? new Date(Date.now() + dueRunbook.intervalSeconds * 1000)
              : new Date(Date.now() + 3600 * 1000),
            lockedAt: null,
            lockOwner: null,
            failureCount: 0,
          },
        });
      } catch {
        const latest = await prisma.runbook.findUnique({ where: { id: dueRunbook.id } });
        const failureCount = (latest?.failureCount ?? 0) + 1;
        const base = Math.max(10, latest?.intervalSeconds ?? dueRunbook.intervalSeconds ?? 60);
        const backoffSeconds = Math.min(base * Math.pow(2, failureCount), 3600);
        await prisma.runbook.update({
          where: { id: dueRunbook.id },
          data: {
            lockedAt: null,
            lockOwner: null,
            failureCount,
            nextRunAt: new Date(Date.now() + backoffSeconds * 1000),
          },
        });
      } finally {
        state.runningGlobal = Math.max(0, state.runningGlobal - 1);
        state.runningLeagues.delete(league.leagueId);
      }
    })();
  }
}

export function ensureAutoRunWorkerStarted() {
  if (process.env.NEXT_RUNTIME === "edge") return;
  const state = getState();
  if (state.started) return;
  state.started = true;
  state.timer = setInterval(() => {
    void runTick();
  }, POLL_MS);
}
